name: Tests

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: install-package
      shell: bash -l {0}
      run: |
        pip install -e .
    - name: test
      shell: bash -l {0}
      run: |
        python -m unittest discover